# TASK 4


 ## 1. Introduction to NumPy


 *   What NumPy is and why it’s important for numerical computations in Python.
 *   Installation of NumPy (pip install numpy).
 *  Understanding its role in data science, machine learning, and scientific computing.





NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform, and matrices.
NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
NumPy stands for Numerical Python.

 NumPy is a Python library.
NumPy is used for working with arrays.
NumPy is short for "Numerical Python".


## 2. Arrays in NumPy

Understanding the concept of ndarray (N-dimensional array).

In [2]:
import numpy 

arr = numpy.array([11,12,13,14,])

print(arr)

[11 12 13 14]


 ### 0-d 

In [24]:
import numpy as np

arr = np.array(3)
print(arr)

3


### 1-d

In [25]:
import numpy as np
arr = np. array([2,3,4])
print(arr)

[2 3 4]


### 2-d

In [28]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### using np.array


In [4]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


 ### using np.zeros

In [7]:
import numpy as np

arr = np.zeros([7])
print(arr)

[0. 0. 0. 0. 0. 0. 0.]


### using np.ones

In [8]:
import numpy as np

arr = np.ones([4])
print(arr)

[1. 1. 1. 1.]


### using np.arange

In [13]:
import numpy as np

arr = np.arange(1,2,3)
print(arr)

[1]


### using np.linspace

In [14]:
import numpy as np

arr = np.linspace(11,20, num=10)
print(arr)

[11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


## indexing 

In [17]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,])
print(arr[3])

4


## slicing 

In [16]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,0])
print(arr[3:6])

[4 5 6]




# 3. Array Operations

* Arithmetic operations on NumPy arrays (addition, subtraction, multiplication, division).
* Broadcasting (performing operations on arrays of different shapes).
* Element-wise operations and functions (e.g., np.sqrt(), np.sin(), np.exp()).

In [18]:
import numpy as np

x = np.array([9,8,7])
y = np.array([1,2,3])
arr= x+y
print(arr)

[10 10 10]


In [19]:
import numpy as np

x = np.array([9,8,7])
y = np.array([1,2,3])

print(y-x)

[-8 -6 -4]


In [20]:
import numpy as np

x = np.array([9,8,7])
y = np.array([1,2,3])
arr= x*y
print(arr)

[ 9 16 21]


In [31]:
import numpy as np

x = np.array([9,8,7])
y = np.array([1,2,3])
arr= x/y
print(arr)

[9.         4.         2.33333333]


# 4. Array Shapes and Reshaping

### shapes 

In [30]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


### Reshaping

In [38]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,])
aarry = arr.reshape(2,5)
print(aarry)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [39]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
aaray = arr. flatten()
print(aaray)

[1 2 3 4 5 6]


### Concatenating and splitting arrays using np.concatenate(), np.vstack(), np.hstack(), np.split().


In [47]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr= np.concatenate((arr1,arr2)) #using concatenate
print(arr)
                      

[1 2 3 4 5 6 7 8]


In [48]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


[[1 2 5 6]
 [3 4 7 8]]


In [50]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr=np.vstack((arr1,arr2)) # using vstack

print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [52]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.hstack((arr1,arr2)) # using hstack

print(arr)

[1 2 3 4 5 6 7 8]


In [53]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,])
new = np.array_split(arr,4)

print(new)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10])]


# 5. Array Manipulation

* Indexing and slicing: understanding multi-dimensional arrays.
* Masking (logical indexing based on conditions).
* Fancy indexing (using arrays of indices to select elements).


In [57]:

arr = np.array ([[1,2,3],[4,5,6],[7,8,9]])

new_index = np.where(arr ==3)[0][0]
print("new index of element 3:",new_index)

new index of element 3: 0


In [62]:
import numpy as np

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])

new_indices = np.where(arr > 60 )[0]

print("row are greter than 60:",new_index)

row are greter than 60: 0


# 6. Mathematical Functions

* Universal functions (ufuncs) like np.add(), np.subtract(), np.multiply().
* Statistical functions: np.mean(), np.median(), np.std(), np.var(), np.min(), np.max().
* Linear algebra functions: np.dot(), np.matmul(), np.linalg.inv(), np.linalg.eig().

In [9]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = np.add(array1, array2)
print(result)

[5 7 9]


In [11]:
import numpy as np

array1 = np.array([7, 9, 17])
array2 = np.array([4, 5, 6])
result = np.subtract(array1, array2)
print(result)

[ 3  4 11]


In [14]:
import numpy as np

array1 = np.array([12, 78, 93])
array2 = np.array([4, 5, 6])
result = np.multiply(array1, array2)
print(result)

[ 48 390 558]


###  Statistical functions: np.mean(), np.median(), np.std(), np.var(), np.min(), np.max().

In [1]:
import numpy as np
ap11= np.array([11,12,13])
xyz = np.mean(ap11)
print(xyz)

12.0


In [2]:
import numpy as np
ap11= np.array([11,12,13,14,15])
xyz = np.median(ap11)
print(xyz)

13.0


In [3]:
import numpy as np
ap11= np.array([11,12,13,14,15])
xyz = np.std(ap11)
print(xyz)

1.4142135623730951


In [4]:
import numpy as np
ap11= np.array([11,12,13,14,15])
xyz = np.var(ap11)
print(xyz)

2.0


In [5]:
import numpy as np
ap11= np.array([11,12,13,14,15])
xyz = np.max(ap11)
print(xyz)

15


### Linear algebra functions: np.dot(), np.matmul(), np.linalg.inv(), np.linalg.eig().


In [14]:

import numpy as geek

prod = geek.dot(5, 5)
print("Dot Product of scalar values : ", prod)

vector_x = 3 + 2j
vector_y = 6 + 7j

prod = geek.dot(vector_x, vector_y)
print("Dot Product : ", prod)


Dot Product of scalar values :  25
Dot Product :  (4+33j)


In [18]:
import numpy.matlib 
import numpy as np 

x = [[2,0],[0,1]] 
y = [[4,1],[6,5]] 
print (np.matmul(x,y))


[[8 2]
 [6 5]]


In [25]:

import numpy as np
 
Ap = np.array([[62,11, 21],
              [41, -12, 15],
              [2, 8, 7]])
 

print("Rank of A:", np.linalg.matrix_rank(Ap))
 
print("\nTrace of A:", np.trace(Ap))
 
print("\nDeterminant of A:", np.linalg.det(Ap)) # np.linalg.det
 
print("\nInverse of A:\n", np.linalg.inv(Ap)) # np.linalg.inv
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(Ap, 3))

Rank of A: 3

Trace of A: 57

Determinant of A: -8082.999999999989

Inverse of A:
 [[ 0.02523815 -0.0112582  -0.05158976]
 [ 0.03179513 -0.04849685  0.00853643]
 [-0.04354819  0.05864159  0.14784115]]

Matrix A raised to power 3:
 [[301560  52003 113145]
 [159847  20588  59907]
 [ 28576   7030  10993]]
